CONTROLLER_HEART_BEAT_EXPIRATION = 30
WORKER_HEART_BEAT_INTERVAL = 15

LOGDIR = "."

# Model Constants
IGNORE_INDEX = -100
AUDIO_TOKEN_INDEX = -200
DEFAULT_AUDIO_TOKEN = "<|im_audio|>"
DEFAULT_AUDIO_START_TOKEN = "<|im_audio_start|>"
DEFAULT_AUDIO_END_TOKEN = "<|im_audio_end|>"
DEFAULT_TTS_START_TOKEN = "<|im_tts_start|>"
DEFAULT_TTS_END_TOKEN = "<|im_tts_end|>"

